### ISSUE TITLE
License and Reference

### ISSUE THREAD

**Issue by IcarusWizard** [Kedreamix/MAE-for-CIFAR#2]
Hi author,

I just encounter your repo and find it is intriguingly similar to [my repo](https://github.com/IcarusWizard/MAE) that was open-sourced two years ago.

I am fine and glad if you use my code base for the purpose of study. But I should highlight my code was published under MIT license which means others can copy and reuse the code **under the condition of "the copyright notice and this permission notice shall be included in all copies or substantial portions of the Software"**.

Thus, please add MIT license to your code base and make reference and link to the origin repo. Thank you.

**Comment by Kedreamix** [comment]
Hi,

Thank you for bringing this to my attention. I apologize for any confusion or inconvenience my actions may have caused. I understand that your code was published under the MIT License, and I should have included a copyright notice and reference to your original repository.

I want to assure you that I have not intentionally used your code without permission and I am glad to comply with your request. I will add the appropriate licensing information, as well as a reference and link to your repository, to my project as soon as possible.

Please let me know if there is anything else I can do to rectify this situation. Thank you again for bringing this to my attention.

Best regards,
Kedreamix

**Comment by IcarusWizard** [comment]
Thanks for the quick response. It is important to explicitly clarify the origin of the code rather than a vague reference. 
For example, you can state in the readme that the repo is translated and commented upon https://github.com/IcarusWizard/MAE.

**Comment by Kedreamix** [comment]
I will take your suggestion into consideration and update the readme file to explicitly state that the repository at https://github.com/IcarusWizard/MAE is a translation and has been commented upon. I believe this will provide valuable context for anyone interested in the code.

Again, thank you for bringing this to my attention and for your helpful suggestion. Please let me know if you have any further feedback or concerns.

**Comment by IcarusWizard** [comment]
I think you are doing in the correct way. Thanks for your cooperation.
