### ISSUE TITLE
result

### ISSUE THREAD

**Issue by caiusy** [Kedreamix/MAE-for-CIFAR#3]
ViT-T w/o pretrain   76.04825
ViT-T w/ pretrain     89.4877
只有显卡不同，显卡是A40

**Comment by Kedreamix** [comment]
看起来还是体现了MAE的好处，不过似乎without pretrain的acc提升了，也可能有一些版本问题

**Comment by caiusy** [comment]
> 看起来还是体现了MAE的好处，不过似乎without pretrain的acc提升了，也可能有一些版本问题

是的 ， 使用预训练模型，第一个epoch就到了82.63
