### ISSUE TITLE
加载Releases里的vit-classifier-pretrain.pth模型，timm的模块找不到？

### ISSUE THREAD

**Issue by Yue021130** [Kedreamix/MAE-for-CIFAR#4]
![图片](https://github.com/Kedreamix/MAE-for-CIFAR/assets/108062406/3d90c64a-c000-4eb7-8aee-362afe7f596a)
如上图，a.pth就是Releases里的vit-classifier-pretrain.pth模型。
![图片](https://github.com/Kedreamix/MAE-for-CIFAR/assets/108062406/77cbf1a1-7cf5-45a6-81e1-dcfb54b03e9c)
上图是我的timm库版本。
降低timm版本后也没有解决问题。请问timm的版本具体要是啥？

**Comment by Kedreamix** [comment]
emmmm，这个可能有点忘记啦，我记得我当时用的还是比较新的版本好像，可以尝试0.8
